---
- hosts: civicrm
  become_user: "{{pac}}-{{user}}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_common_remote_group: "{{pac}}"
    # avoid error: Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user
    #allow_world_readable_tmpfiles: true

  tasks:
  #################################
  ## setup the user, the domain, the database
  #################################
  - name: Create user, domain and database
    import_tasks: tasks/hslamp.yml

  - name: Sleep to avoid issue invalid user for temporary files
    pause:
      seconds: 10
