---
- hosts: civicrm
  become_user: "{{pac}}-{{user}}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

  # check if update was successful:
  # ~/composer/composer.phar outdated "drupal/*"
  # ~/composer/composer.phar outdated "civicrm/*"

  tasks:
  - name: upload php script for Drush
    become: yes
    template: dest="/home/pacs/{{pac}}/users/{{user}}/bin/php" src="templates/php" mode=0700

  - name: Put site into maintenance mode
    become: yes
    shell: |
      export PATH=$HOME/bin:$PATH
      vendor/drush/drush/drush state:set system.maintenance_mode 1 --input-format=integer || exit -1
      vendor/drush/drush/drush cache:rebuild || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/drupal-civicrm"

  - name: Update Drupal with composer and drush
    become: yes
    shell: |
      export PATH=$HOME/bin:$PATH
      # to avoid problem: Could not delete /home/pacs/.../drupal-civicrm/web/sites/default/default.settings.php
      chmod u+w web/sites/default || exit -1
      # see https://www.drupal.org/docs/updating-drupal/updating-drupal-core-via-composer
      COMPOSER_COMPILE=all ~/composer/composer.phar --no-interaction update drupal/core "drupal/core-*" --with-all-dependencies || exit -1
      COMPOSER_COMPILE=all ~/composer/composer.phar --no-interaction update drupal/smtp --with-all-dependencies || exit -1
      echo "yes" | vendor/drush/drush/drush updatedb -l https://{{domain}}/ || exit -1
      vendor/drush/drush/drush cache:rebuild -l https://{{domain}}/  || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/drupal-civicrm"

  - name: Update CiviCRM with composer
    become: yes
    shell: |
      export PATH=$HOME/bin:$PATH
      # see https://docs.civicrm.org/sysadmin/en/latest/upgrade/drupal8/
      ##COMPOSER_COMPILE=all ~/composer/composer.phar --no-interaction update -v civicrm/civicrm-asset-plugin || exit -1
      #COMPOSER_COMPILE=all ~/composer/composer.phar --no-interaction update -v civicrm/civicrm-{core,packages,drupal-8} --with-all-dependencies || exit -1

      # or for a bigger upgrade:
      ~/composer/composer.phar config --no-plugins allow-plugins.civicrm/civicrm-asset-plugin true || exit -1
      ~/composer/composer.phar config --no-plugins allow-plugins.civicrm/composer-downloads-plugin true || exit -1
      ~/composer/composer.phar config --no-plugins allow-plugins.civicrm/composer-compile-plugin true || exit -1
      COMPOSER_COMPILE=all ~/composer/composer.phar --no-interaction require -v civicrm/civicrm-asset-plugin:~1.1 || exit -1
      COMPOSER_COMPILE=all ~/composer/composer.phar --no-interaction require -v civicrm/civicrm-{core,packages,drupal-8}:{{civicrm_version}} --with-all-dependencies || exit -1

      vendor/drush/drush/drush updatedb -l https://{{domain}}/ || exit -1
      vendor/drush/drush/drush cache:rebuild -l https://{{domain}}/  || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/drupal-civicrm"

  - name: download civicrm translations directly
    become: yes
    unarchive:
      src: https://sourceforge.net/projects/civicrm/files/civicrm-stable/{{civicrm_version}}/civicrm-{{civicrm_version}}-l10n.tar.gz/download
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/vendor/civicrm/civicrm-core/
      extra_opts: [--strip-components=1] # to avoid the civicrm directory
      creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/vendor/civicrm/civicrm-core/i10n
    when: url_proxy is not defined

  - name: download civicrm translations from proxy
    become: yes
    unarchive:
      src: "{{url_proxy}}/civicrm-{{civicrm_version}}-l10n.tar.gz"
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/vendor/civicrm/civicrm-core/
      extra_opts: [--strip-components=1] # to avoid the civicrm directory
      creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/vendor/civicrm/civicrm-core/i10n
    when: url_proxy is defined

  - name: update CiviCRM with cv
    become: yes
    shell: |
      export PATH=$HOME/bin:$PATH
      # see https://docs.civicrm.org/sysadmin/en/latest/upgrade/drupal8/
      echo "yes" | /home/pacs/{{pac}}/users/{{user}}/bin/cv.phar upgrade:db || exit -1
      # clear cache
      /home/pacs/{{pac}}/users/{{user}}/bin/cv.phar flush || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/drupal-civicrm"

  - name: Put site back online
    become: yes
    shell: |
      export PATH=$HOME/bin:$PATH
      vendor/drush/drush/drush state:set system.maintenance_mode 0 --input-format=integer || exit -1
      vendor/drush/drush/drush cache:rebuild || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/drupal-civicrm"
