---
- hosts: civicrm
  become_user: "{{pac}}-{{user}}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_common_remote_group: "{{pac}}"
    # avoid error: Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user
    #allow_world_readable_tmpfiles: true

  tasks:

  ################################################
  ## add extensions for SEPA direct debit and BIC
  ################################################

  # see https://github.com/Project60/org.project60.sepa/releases
  - name: install extension SEPA direct debit integration with civicrm
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext/org.project60.sepa-master
      src: https://github.com/Project60/org.project60.sepa/archive/refs/heads/master.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext

  - name: install extension SEPA direct debit payment processor
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext/org.project60.sepapp-master
      src: https://github.com/Project60/org.project60.sepapp/archive/refs/heads/master.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext

  - name: install extension Little BIC extension
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext/org.project60.bic-master
      src: https://github.com/Project60/org.project60.bic/archive/refs/heads/master.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext

  - name: install extension Recurring Buttons
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext/recurringbuttons-master
      src: https://lab.civicrm.org/extensions/recurringbuttons/-/archive/master/recurringbuttons-master.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext

  - name: install extension Radio Buttons
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext/radiobuttons-master
      src: https://lab.civicrm.org/extensions/radiobuttons/-/archive/master/radiobuttons-master.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext

  ################################################
  ## add extensions for Donations
  ################################################
  - name: install extension DonRec
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext/de.systopia.donrec
      src: https://github.com/systopia/de.systopia.donrec/releases/download/2.1.0/de.systopia.donrec-2.1.0.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext

  # see https://github.com/Project60/org.project60.banking/releases
  - name: switch to CiviBanking
    become: yes
    set_fact:
      extension_name: 'org.project60.banking'
      extension_new_version: '0.8.2'
      extension_url: 'https://github.com/Project60/org.project60.banking/releases/download/0.8.2/org.project60.banking-0.8.2.tar.gz'
  - name: install extension CiviBanking
    import_tasks: tasks/update_civi_extension.yml

  ################################################
  ## add extensions for Theme
  ################################################
  - name: install extension ShoreDitch
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext/org.civicrm.shoreditch-1.0.0-beta.12
      src: https://github.com/civicrm/org.civicrm.shoreditch/archive/refs/tags/1.0.0-beta.12.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext
