---
- name: install extension
  become: yes
  unarchive:
    creates: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext/{{extension_name}}
    src: "{{extension_url}}"
    remote_src: yes
    dest: /home/pacs/{{pac}}/users/{{user}}/drupal-civicrm/web/sites/default/files/civicrm/ext
  when: extension_exists.stat.exists and extension_cur_version.stdout != extension_new_version

- name: remember extension version
  become: yes
  template: dest="/home/pacs/{{pac}}/users/{{user}}/.ansible_{{extension_name}}" src="templates/ansible_extension_version" mode=0644
  when: extension_exists.stat.exists and extension_cur_version.stdout != extension_new_version
